import { useState, useContext, useEffect } from 'react'
import { formatDistanceToNow } from 'date-fns'
import { supabase } from '~/lib/Store'
import { UserContext } from '../lib/UserContext'
import MessageReactions from './MessageReactions'
import ThreadPanel from './ThreadPanel'
import classNames from 'classnames'

export default function Message({ message, showThread = false, onThreadClick }) {
  const { user } = useContext(UserContext)
  const [replyCount, setReplyCount] = useState(message.reply_count || 0)
  const [isThreadVisible, setIsThreadVisible] = useState(false)

  useEffect(() => {
    if (message.read_by && !message.read_by.includes(user.id)) {
      // Mark message as read
      const newReadBy = [...(message.read_by || []), user.id]
      supabase
        .from('messages')
        .update({ read_by: newReadBy })
        .eq('id', message.id)
        .then(({ error }) => {
          if (error) console.error('Error marking message as read:', error)
        })
    }
  }, [message.id, message.read_by, user.id])

  const messageClasses = classNames(
    'message-container',
    {
      'is-announcement': message.is_announcement,
      'is-ai-generated': message.is_ai_generated,
      'is-pinned': message.is_pinned,
      'is-edited': message.edited_at,
      'is-pending': message.delivery_status === 'pending',
      'is-failed': message.delivery_status === 'failed'
    }
  )

  return (
    <div className={messageClasses}>
      <div className="message-header">
        <Avatar url={message.user?.avatar_url} />
        <div className="message-meta">
          <span className="username">{message.user?.display_name || message.user?.username || 'Unknown User'}</span>
          <span className="timestamp">{formatDate(message.created_at)}</span>
          {message.edited_at && (
            <span className="edited-indicator">(edited)</span>
          )}
          {message.is_announcement && (
            <span className="announcement-badge">Announcement</span>
          )}
          {message.is_pinned && (
            <span className="pinned-badge">📌 Pinned</span>
          )}
        </div>
      </div>
      
      <div className="message-content">
        {message.is_ai_generated && (
          <div className="ai-indicator">
            🤖 Generated by {message.ai_model || 'AI'}
          </div>
        )}
        <div className="message-text">{message.message_text}</div>
        {message.attachments && Object.keys(message.attachments).length > 0 && (
          <div className="attachments">
            {/* Render attachments */}
          </div>
        )}
        {message.mentions && Object.keys(message.mentions).length > 0 && (
          <div className="mentions">
            {/* Render mentions */}
          </div>
        )}
      </div>

      <div className="message-footer">
        <MessageReactions message={message} />
        {message.thread_id && (
          <button 
            className="thread-button"
            onClick={() => {
              setIsThreadVisible(!isThreadVisible)
              if (onThreadClick) onThreadClick(message)
            }}
          >
            {replyCount} {replyCount === 1 ? 'reply' : 'replies'}
          </button>
        )}
        {message.delivery_status === 'failed' && (
          <span className="error-message">Failed to send. Please try again.</span>
        )}
      </div>

      {showThread && isThreadVisible && message.thread_id && (
        <div className="thread-container">
          {/* Thread component would go here */}
        </div>
      )}
    </div>
  )
}