-- Custom types
CREATE TYPE public.app_permission AS ENUM ('channels.delete', 'messages.delete');
CREATE TYPE public.app_role AS ENUM ('admin', 'moderator');
CREATE TYPE public.user_status AS ENUM ('ONLINE', 'OFFLINE');

-- Drop all existing tables in reverse order of dependencies
DROP TABLE IF EXISTS public.slash_commands CASCADE;
DROP TABLE IF EXISTS public.custom_emojis CASCADE;
DROP TABLE IF EXISTS public.call_sessions CASCADE;
DROP TABLE IF EXISTS public.moderation_actions CASCADE;
DROP TABLE IF EXISTS public.notifications CASCADE;
DROP TABLE IF EXISTS public.thread_summaries CASCADE;
DROP TABLE IF EXISTS public.message_reactions CASCADE;
DROP TABLE IF EXISTS public.pinned_messages CASCADE;
DROP TABLE IF EXISTS public.messages CASCADE;
DROP TABLE IF EXISTS public.direct_messages CASCADE;
DROP TABLE IF EXISTS public.dm_room_members CASCADE;
DROP TABLE IF EXISTS public.dm_rooms CASCADE;
DROP TABLE IF EXISTS public.channel_members CASCADE;
DROP TABLE IF EXISTS public.channels CASCADE;
DROP TABLE IF EXISTS public.workspace_members CASCADE;
DROP TABLE IF EXISTS public.workspaces CASCADE;
DROP TABLE IF EXISTS public.ai_documents CASCADE;
DROP TABLE IF EXISTS public.role_permissions CASCADE;
DROP TABLE IF EXISTS public.user_roles CASCADE;
DROP TABLE IF EXISTS public.users CASCADE;

-- Create users table
CREATE TABLE public.users (
  id                UUID PRIMARY KEY,
  email             TEXT UNIQUE NOT NULL,
  username          TEXT UNIQUE NOT NULL,
  display_name      TEXT,
  phone_number      TEXT,
  avatar_url        TEXT,
  description       TEXT,
  status            TEXT,
  faction           TEXT,
  last_seen         TIMESTAMP,
  is_bot            BOOLEAN DEFAULT FALSE,
  preferences       JSONB,
  ai_persona        JSONB,
  gamification      JSONB,
  metadata          JSONB,
  placeholder_col_1 TEXT,
  placeholder_col_2 JSONB,
  created_at        TIMESTAMP DEFAULT now(),
  updated_at        TIMESTAMP DEFAULT now()
);

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

-- Users RLS Policies
CREATE POLICY "Public read of all users"
ON public.users FOR SELECT TO authenticated
USING (true);

CREATE POLICY "Insert your own user row"
ON public.users FOR INSERT TO authenticated
WITH CHECK ( id = auth.uid() );

CREATE POLICY "Update self"
ON public.users FOR UPDATE TO authenticated
USING ( id = auth.uid() )
WITH CHECK ( id = auth.uid() );

CREATE POLICY "Delete self"
ON public.users FOR DELETE TO authenticated
USING ( id = auth.uid() );

-- Create user_roles table
CREATE TABLE public.user_roles (
  id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id   UUID REFERENCES public.users ON DELETE CASCADE NOT NULL,
  role      app_role NOT NULL,
  UNIQUE (user_id, role)
);
COMMENT ON TABLE public.user_roles IS 'Application roles for each user.';

ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow individual read access" 
ON public.user_roles FOR SELECT 
TO authenticated 
USING ( user_id = auth.uid() );

-- Create role_permissions table
CREATE TABLE public.role_permissions (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role         app_role NOT NULL,
  permission   app_permission NOT NULL,
  UNIQUE (role, permission)
);
COMMENT ON TABLE public.role_permissions IS 'Application permissions for each role.';

ALTER TABLE public.role_permissions ENABLE ROW LEVEL SECURITY;

-- Create authorize function
CREATE OR REPLACE FUNCTION public.authorize(
  requested_permission app_permission
)
RETURNS boolean AS $$
DECLARE
  bind_permissions int;
BEGIN
  SELECT count(*)
  FROM public.role_permissions
  WHERE role_permissions.permission = authorize.requested_permission
    AND role_permissions.role = (auth.jwt() ->> 'user_role')::public.app_role
  INTO bind_permissions;
  
  RETURN bind_permissions > 0;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

-- Create ai_documents table
CREATE TABLE public.ai_documents (
  id               UUID PRIMARY KEY,
  owner_user_id    UUID NOT NULL,
  title            TEXT,
  description      TEXT,
  source_type      TEXT,
  content_url      TEXT,
  embedding_refs   JSONB,
  metadata         JSONB,
  created_at       TIMESTAMP DEFAULT now(),
  updated_at       TIMESTAMP DEFAULT now()
);

ALTER TABLE public.ai_documents ENABLE ROW LEVEL SECURITY;

-- AI Documents RLS Policies
CREATE POLICY "Select ai_documents if owner"
ON public.ai_documents FOR SELECT TO authenticated
USING ( owner_user_id = auth.uid() );

CREATE POLICY "Insert your own ai_docs"
ON public.ai_documents FOR INSERT TO authenticated
WITH CHECK ( owner_user_id = auth.uid() );

CREATE POLICY "Update your own ai_docs"
ON public.ai_documents FOR UPDATE TO authenticated
USING ( owner_user_id = auth.uid() )
WITH CHECK ( owner_user_id = auth.uid() );

CREATE POLICY "Delete your own ai_docs"
ON public.ai_documents FOR DELETE TO authenticated
USING ( owner_user_id = auth.uid() );

-- Create workspaces table
CREATE TABLE public.workspaces (
  id               UUID PRIMARY KEY,
  name             TEXT NOT NULL,
  owner_id         UUID NOT NULL,
  workspace_type   TEXT DEFAULT 'standard',
  metadata         JSONB,
  placeholder_1    TEXT,
  placeholder_2    JSONB,
  created_at       TIMESTAMP DEFAULT now(),
  updated_at       TIMESTAMP DEFAULT now()
);

ALTER TABLE public.workspaces ENABLE ROW LEVEL SECURITY;

-- Workspaces RLS Policies
CREATE POLICY "Public read of all workspaces"
ON public.workspaces FOR SELECT TO authenticated
USING (true);

CREATE POLICY "Insert workspace"
ON public.workspaces FOR INSERT TO authenticated
WITH CHECK ( owner_id = auth.uid() );

CREATE POLICY "Update if workspace owner"
ON public.workspaces FOR UPDATE TO authenticated
USING ( owner_id = auth.uid() )
WITH CHECK ( owner_id = auth.uid() );

CREATE POLICY "Delete if workspace owner"
ON public.workspaces FOR DELETE TO authenticated
USING ( owner_id = auth.uid() );

-- Create workspace_members table
CREATE TABLE public.workspace_members (
  id             UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  workspace_id   UUID NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE,
  user_id        UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  role           TEXT NOT NULL CHECK (role IN ('owner', 'admin', 'member', 'guest')),
  permissions    JSONB DEFAULT '{}',
  metadata       JSONB DEFAULT '{}',
  created_at     TIMESTAMP DEFAULT now(),
  updated_at     TIMESTAMP DEFAULT now()
);

-- Add unique constraint to prevent duplicate memberships
ALTER TABLE public.workspace_members 
ADD CONSTRAINT workspace_members_workspace_user_unique 
UNIQUE (workspace_id, user_id);

-- Add indexes for performance
CREATE INDEX idx_workspace_members_workspace_id ON public.workspace_members(workspace_id);
CREATE INDEX idx_workspace_members_user_id ON public.workspace_members(user_id);
CREATE INDEX idx_workspace_members_role ON public.workspace_members(role);
CREATE INDEX idx_workspace_members_created_at ON public.workspace_members(created_at);

ALTER TABLE public.workspace_members ENABLE ROW LEVEL SECURITY;

-- Workspace Members RLS Policies
CREATE POLICY "Public read of workspace_members"
ON public.workspace_members FOR SELECT TO authenticated
USING (true);

CREATE POLICY "Insert membership"
ON public.workspace_members FOR INSERT TO authenticated
WITH CHECK ( user_id = auth.uid() );

CREATE POLICY "Update your own membership"
ON public.workspace_members FOR UPDATE TO authenticated
USING ( user_id = auth.uid() )
WITH CHECK ( user_id = auth.uid() );

CREATE POLICY "Delete your own membership"
ON public.workspace_members FOR DELETE TO authenticated
USING ( user_id = auth.uid() );

-- Create channels table
CREATE TABLE public.channels (
  id             UUID PRIMARY KEY,
  name           TEXT NOT NULL,
  slug           TEXT NOT NULL,
  workspace_id   UUID NOT NULL,
  created_by     UUID NOT NULL,
  description    TEXT,
  is_private     BOOLEAN DEFAULT false,
  metadata       JSONB,
  created_at     TIMESTAMP DEFAULT now(),
  updated_at     TIMESTAMP DEFAULT now(),
  FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
  FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE CASCADE
);

ALTER TABLE public.channels ENABLE ROW LEVEL SECURITY;

-- Add indexes for performance
CREATE INDEX idx_channels_workspace_id ON public.channels(workspace_id);
CREATE INDEX idx_channels_created_by ON public.channels(created_by);
CREATE INDEX idx_channels_created_at ON public.channels(created_at);

-- Channels RLS Policies
CREATE POLICY "Select all channels"
ON public.channels FOR SELECT TO authenticated
USING (true);

CREATE POLICY "Insert channel"
ON public.channels FOR INSERT TO authenticated
WITH CHECK (created_by = auth.uid());

CREATE POLICY "Update channel if creator"
ON public.channels FOR UPDATE TO authenticated
USING (created_by = auth.uid())
WITH CHECK (created_by = auth.uid());

CREATE POLICY "Delete channel if creator"
ON public.channels FOR DELETE TO authenticated
USING (created_by = auth.uid());

-- Create channel_members table
CREATE TABLE public.channel_members (
  id             UUID PRIMARY KEY,
  channel_id     UUID NOT NULL,
  user_id        UUID NOT NULL,
  role           TEXT NOT NULL CHECK (role IN ('member', 'moderator', 'admin')),
  metadata       JSONB NOT NULL DEFAULT '{}',
  created_at     TIMESTAMP DEFAULT now(),
  updated_at     TIMESTAMP DEFAULT now(),
  FOREIGN KEY (channel_id) REFERENCES channels(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  UNIQUE (channel_id, user_id)
);

ALTER TABLE public.channel_members ENABLE ROW LEVEL SECURITY;

-- Add indexes for performance
CREATE INDEX idx_channel_members_channel_id ON public.channel_members(channel_id);
CREATE INDEX idx_channel_members_user_id ON public.channel_members(user_id);
CREATE INDEX idx_channel_members_role ON public.channel_members(role);
CREATE INDEX idx_channel_members_created_at ON public.channel_members(created_at);

-- Channel Members RLS Policies
CREATE POLICY "Select all channel_members"
ON public.channel_members FOR SELECT TO authenticated
USING (true);

CREATE POLICY "Insert channel membership"
ON public.channel_members FOR INSERT TO authenticated
WITH CHECK (user_id = auth.uid());

CREATE POLICY "Update channel membership if self"
ON public.channel_members FOR UPDATE TO authenticated
USING (user_id = auth.uid())
WITH CHECK (user_id = auth.uid());

CREATE POLICY "Delete channel membership if self"
ON public.channel_members FOR DELETE TO authenticated
USING (user_id = auth.uid());

-- Create dm_rooms table
CREATE TABLE public.dm_rooms (
  id             UUID PRIMARY KEY,
  room_name      TEXT NOT NULL,
  is_group       BOOLEAN DEFAULT false,
  workspace_id   UUID NOT NULL,
  metadata       JSONB,
  placeholder_1  TEXT,
  created_at     TIMESTAMP DEFAULT now(),
  updated_at     TIMESTAMP DEFAULT now(),
  FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE
);

ALTER TABLE public.dm_rooms ENABLE ROW LEVEL SECURITY;

-- DM Rooms RLS Policies
CREATE POLICY "Select all dm_rooms"
ON public.dm_rooms FOR SELECT TO authenticated
USING (true);

CREATE POLICY "Insert dm_room"
ON public.dm_rooms FOR INSERT TO authenticated
WITH CHECK (true);

CREATE POLICY "Update dm_room open"
ON public.dm_rooms FOR UPDATE TO authenticated
USING (true)
WITH CHECK (true);

CREATE POLICY "Delete dm_room open"
ON public.dm_rooms FOR DELETE TO authenticated
USING (true);

-- Add indexes for performance
CREATE INDEX idx_dm_rooms_workspace_id ON public.dm_rooms(workspace_id);
CREATE INDEX idx_dm_rooms_created_at ON public.dm_rooms(created_at);

-- Create dm_room_members table first
CREATE TABLE public.dm_room_members (
  id             UUID PRIMARY KEY,
  dm_room_id     UUID NOT NULL,
  user_id        UUID NOT NULL,
  role           TEXT NOT NULL CHECK (role IN ('admin', 'member')),
  metadata       JSONB NOT NULL DEFAULT '{}',
  placeholder_1  TEXT,
  created_at     TIMESTAMP DEFAULT now(),
  updated_at     TIMESTAMP DEFAULT now(),
  UNIQUE (dm_room_id, user_id)
);

-- Then add foreign key constraints
ALTER TABLE public.dm_room_members
ADD CONSTRAINT fk_dm_room_members_room
FOREIGN KEY (dm_room_id) REFERENCES dm_rooms(id) ON DELETE CASCADE,
ADD CONSTRAINT fk_dm_room_members_user
FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

-- Add indexes for dm_room_members
CREATE INDEX idx_dm_room_members_room_id ON public.dm_room_members(dm_room_id);
CREATE INDEX idx_dm_room_members_user_id ON public.dm_room_members(user_id);
CREATE INDEX idx_dm_room_members_role ON public.dm_room_members(role);
CREATE INDEX idx_dm_room_members_created_at ON public.dm_room_members(created_at);

ALTER TABLE public.dm_room_members ENABLE ROW LEVEL SECURITY;

-- DM Room Members RLS Policies
CREATE POLICY "Select all dm_room_members"
ON public.dm_room_members FOR SELECT TO authenticated
USING (true);

CREATE POLICY "Insert dm_room_members"
ON public.dm_room_members FOR INSERT TO authenticated
WITH CHECK (true);

CREATE POLICY "Update dm_room_members if self"
ON public.dm_room_members FOR UPDATE TO authenticated
USING (user_id = auth.uid())
WITH CHECK (user_id = auth.uid());

CREATE POLICY "Delete dm_room_members if self"
ON public.dm_room_members FOR DELETE TO authenticated
USING (user_id = auth.uid());

-- Create direct_messages table
CREATE TABLE public.direct_messages (
  id             UUID PRIMARY KEY,
  dm_room_id     UUID NOT NULL,
  sender_id      UUID NOT NULL,
  parent_id      UUID,
  message_text   TEXT,
  attachments    JSONB,
  mentions       JSONB,
  metadata       JSONB,
  created_at     TIMESTAMP DEFAULT now(),
  updated_at     TIMESTAMP DEFAULT now(),
  placeholder_1  TEXT
);

ALTER TABLE public.direct_messages ENABLE ROW LEVEL SECURITY;

-- Direct Messages RLS Policies
CREATE POLICY "Select direct messages open"
ON public.direct_messages FOR SELECT TO authenticated
USING (true);

CREATE POLICY "Insert DM if user is sender"
ON public.direct_messages FOR INSERT TO authenticated
WITH CHECK ( sender_id = auth.uid() );

CREATE POLICY "Update own DM"
ON public.direct_messages FOR UPDATE TO authenticated
USING ( sender_id = auth.uid() )
WITH CHECK ( sender_id = auth.uid() );

CREATE POLICY "Delete own DM"
ON public.direct_messages FOR DELETE TO authenticated
USING ( sender_id = auth.uid() );

-- Create messages table
CREATE TABLE public.messages (
  id                   UUID PRIMARY KEY,
  channel_id           UUID NOT NULL,
  user_id              UUID NOT NULL,
  workspace_id         UUID NOT NULL,
  message_text         TEXT NOT NULL,
  parent_id            UUID,
  thread_id            UUID,
  edited_at            TIMESTAMP,
  edited_by            UUID,
  attachments          JSONB DEFAULT '{}',
  mentions             JSONB DEFAULT '{}',
  metadata             JSONB DEFAULT '{}',
  is_pinned           BOOLEAN DEFAULT false,
  reactions           JSONB DEFAULT '{}',
  reply_count         INTEGER DEFAULT 0,
  is_announcement     BOOLEAN DEFAULT false,
  created_at          TIMESTAMP DEFAULT now(),
  updated_at          TIMESTAMP DEFAULT now(),
  FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
  FOREIGN KEY (channel_id) REFERENCES channels(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Add indexes
CREATE INDEX idx_messages_created_at ON public.messages(created_at);
CREATE INDEX idx_messages_thread_id ON public.messages(thread_id);
CREATE INDEX idx_messages_user_id ON public.messages(user_id);
CREATE INDEX idx_messages_workspace_id ON public.messages(workspace_id);

ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

-- Messages RLS Policies
CREATE POLICY "Select all channel messages"
ON public.messages FOR SELECT TO authenticated
USING (true);

CREATE POLICY "Insert message if user is sender"
ON public.messages FOR INSERT TO authenticated
WITH CHECK ( user_id = auth.uid() );

CREATE POLICY "Update own message"
ON public.messages FOR UPDATE TO authenticated
USING ( user_id = auth.uid() )
WITH CHECK ( user_id = auth.uid() );

CREATE POLICY "Delete own message"
ON public.messages FOR DELETE TO authenticated
USING ( user_id = auth.uid() );

-- Create pinned_messages table
CREATE TABLE public.pinned_messages (
  id               UUID PRIMARY KEY,
  message_type     TEXT NOT NULL,
  message_id       UUID NOT NULL,
  pinned_by        UUID NOT NULL,
  pinned_at        TIMESTAMP DEFAULT now(),
  metadata         JSONB,
  placeholder_1    TEXT,
  created_at       TIMESTAMP DEFAULT now(),
  updated_at       TIMESTAMP DEFAULT now()
);

ALTER TABLE public.pinned_messages ENABLE ROW LEVEL SECURITY;

-- Pinned Messages RLS Policies
CREATE POLICY "Select pinned_messages all"
ON public.pinned_messages FOR SELECT TO authenticated
USING (true);

CREATE POLICY "Insert pinned_messages"
ON public.pinned_messages FOR INSERT TO authenticated
WITH CHECK ( pinned_by = auth.uid() );

CREATE POLICY "Update pinned_messages if pinned_by self"
ON public.pinned_messages FOR UPDATE TO authenticated
USING ( pinned_by = auth.uid() )
WITH CHECK ( pinned_by = auth.uid() );

CREATE POLICY "Delete pinned_messages if pinned_by self"
ON public.pinned_messages FOR DELETE TO authenticated
USING ( pinned_by = auth.uid() );

-- Create message_reactions table
CREATE TABLE public.message_reactions (
  id               UUID PRIMARY KEY,
  message_type     TEXT,
  message_id       UUID NOT NULL,
  user_id          UUID NOT NULL,
  emoji            TEXT,
  metadata         JSONB,
  created_at       TIMESTAMP DEFAULT now(),
  updated_at       TIMESTAMP DEFAULT now(),
  placeholder_1    TEXT
);

ALTER TABLE public.message_reactions ENABLE ROW LEVEL SECURITY;

-- Message Reactions RLS Policies
CREATE POLICY "Select all message_reactions"
ON public.message_reactions FOR SELECT TO authenticated
USING (true);

CREATE POLICY "Insert reaction"
ON public.message_reactions FOR INSERT TO authenticated
WITH CHECK ( user_id = auth.uid() );

CREATE POLICY "Update own reaction"
ON public.message_reactions FOR UPDATE TO authenticated
USING ( user_id = auth.uid() )
WITH CHECK ( user_id = auth.uid() );

CREATE POLICY "Delete own reaction"
ON public.message_reactions FOR DELETE TO authenticated
USING ( user_id = auth.uid() );

-- Create thread_summaries table
CREATE TABLE public.thread_summaries (
  id                UUID PRIMARY KEY,
  channel_id        UUID,
  parent_message_id UUID,
  summary_text      TEXT NOT NULL,
  pinned            BOOLEAN DEFAULT false,
  metadata          JSONB,
  created_at        TIMESTAMP DEFAULT now(),
  updated_at        TIMESTAMP DEFAULT now()
);

ALTER TABLE public.thread_summaries ENABLE ROW LEVEL SECURITY;

-- Thread Summaries RLS Policies
CREATE POLICY "Select thread_summaries"
ON public.thread_summaries FOR SELECT TO authenticated
USING (true);

CREATE POLICY "Insert thread_summaries"
ON public.thread_summaries FOR INSERT TO authenticated
WITH CHECK (true);

CREATE POLICY "Update thread_summaries open"
ON public.thread_summaries FOR UPDATE TO authenticated
USING (true)
WITH CHECK (true);

CREATE POLICY "Delete thread_summaries open"
ON public.thread_summaries FOR DELETE TO authenticated
USING (true);

-- Create notifications table
CREATE TABLE public.notifications (
  id                UUID PRIMARY KEY,
  user_id           UUID NOT NULL,
  notification_type TEXT,
  title             TEXT,
  body              TEXT,
  link              TEXT,
  is_read           BOOLEAN DEFAULT false,
  metadata          JSONB,
  placeholder_1     TEXT,
  created_at        TIMESTAMP DEFAULT now(),
  updated_at        TIMESTAMP DEFAULT now()
);

ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

-- Notifications RLS Policies
CREATE POLICY "Select notifications if user is recipient"
ON public.notifications FOR SELECT TO authenticated
USING ( user_id = auth.uid() );

CREATE POLICY "Insert notifications"
ON public.notifications FOR INSERT TO authenticated
WITH CHECK ( user_id = auth.uid() );

CREATE POLICY "Update notifications if user is recipient"
ON public.notifications FOR UPDATE TO authenticated
USING ( user_id = auth.uid() )
WITH CHECK ( user_id = auth.uid() );

CREATE POLICY "Delete notifications if user is recipient"
ON public.notifications FOR DELETE TO authenticated
USING ( user_id = auth.uid() );

-- Create moderation_actions table
CREATE TABLE public.moderation_actions (
  id               UUID PRIMARY KEY,
  workspace_id     UUID,
  channel_id       UUID,
  acted_upon_id    UUID NOT NULL,
  acted_by_id      UUID NOT NULL,
  action_type      TEXT NOT NULL,
  reason           TEXT,
  expires_at       TIMESTAMP,
  metadata         JSONB,
  created_at       TIMESTAMP DEFAULT now()
);

ALTER TABLE public.moderation_actions ENABLE ROW LEVEL SECURITY;

-- Moderation Actions RLS Policies
CREATE POLICY "Select all moderation_actions"
ON public.moderation_actions FOR SELECT TO authenticated
USING (true);

CREATE POLICY "Insert moderation actions"
ON public.moderation_actions FOR INSERT TO authenticated
WITH CHECK ( acted_by_id = auth.uid() );

CREATE POLICY "Update moderation actions open"
ON public.moderation_actions FOR UPDATE TO authenticated
USING (true)
WITH CHECK (true);

CREATE POLICY "Delete moderation actions open"
ON public.moderation_actions FOR DELETE TO authenticated
USING (true);

-- Create call_sessions table
CREATE TABLE public.call_sessions (
  id             UUID PRIMARY KEY,
  call_type      TEXT DEFAULT 'user_to_user',
  channel_id     UUID,
  dm_room_id     UUID,
  initiator_id   UUID NOT NULL,
  participants   JSONB,
  started_at     TIMESTAMP DEFAULT now(),
  ended_at       TIMESTAMP,
  metadata       JSONB,
  placeholder_1  TEXT,
  created_at     TIMESTAMP DEFAULT now(),
  updated_at     TIMESTAMP DEFAULT now()
);

ALTER TABLE public.call_sessions ENABLE ROW LEVEL SECURITY;

-- Call Sessions RLS Policies
CREATE POLICY "Select call_sessions"
ON public.call_sessions FOR SELECT TO authenticated
USING (true);

CREATE POLICY "Insert call_sessions"
ON public.call_sessions FOR INSERT TO authenticated
WITH CHECK ( initiator_id = auth.uid() );

CREATE POLICY "Update call_sessions open"
ON public.call_sessions FOR UPDATE TO authenticated
USING (true)
WITH CHECK (true);

CREATE POLICY "Delete call_sessions open"
ON public.call_sessions FOR DELETE TO authenticated
USING (true);

-- Create custom_emojis table
CREATE TABLE public.custom_emojis (
  id            UUID PRIMARY KEY,
  emoji_name    TEXT UNIQUE NOT NULL,
  image_url     TEXT NOT NULL,
  is_global     BOOLEAN DEFAULT true,
  metadata      JSONB,
  placeholder_1 TEXT,
  created_at    TIMESTAMP DEFAULT now(),
  updated_at    TIMESTAMP DEFAULT now()
);

ALTER TABLE public.custom_emojis ENABLE ROW LEVEL SECURITY;

-- Custom Emojis RLS Policies
CREATE POLICY "Select all custom_emojis"
ON public.custom_emojis FOR SELECT TO authenticated
USING (true);

CREATE POLICY "Insert custom_emojis"
ON public.custom_emojis FOR INSERT TO authenticated
WITH CHECK (true);

CREATE POLICY "Update custom_emojis open"
ON public.custom_emojis FOR UPDATE TO authenticated
USING (true)
WITH CHECK (true);

CREATE POLICY "Delete custom_emojis open"
ON public.custom_emojis FOR DELETE TO authenticated
USING (true);

-- Create slash_commands table
CREATE TABLE public.slash_commands (
  id            UUID PRIMARY KEY,
  command       TEXT NOT NULL,
  description   TEXT,
  permissions   JSONB,
  metadata      JSONB,
  placeholder_1 TEXT,
  created_at    TIMESTAMP DEFAULT now(),
  updated_at    TIMESTAMP DEFAULT now()
);

ALTER TABLE public.slash_commands ENABLE ROW LEVEL SECURITY;

-- Slash Commands RLS Policies
CREATE POLICY "Select slash_commands"
ON public.slash_commands FOR SELECT TO authenticated
USING (true);

CREATE POLICY "Manage slash_commands"
ON public.slash_commands FOR ALL TO authenticated
USING (true)
WITH CHECK (true);

-- Create handle_new_user trigger function
CREATE OR REPLACE FUNCTION public.handle_new_user() 
RETURNS trigger AS $$
DECLARE is_admin boolean;
BEGIN
  INSERT INTO public.users (id, username, email)
  VALUES (new.id, new.email, new.email);
  
  SELECT count(*) = 1 FROM auth.users INTO is_admin;
  
  IF position('+supaadmin@' in new.email) > 0 THEN
    INSERT INTO public.user_roles (user_id, role) VALUES (new.id, 'admin');
  ELSIF position('+supamod@' in new.email) > 0 THEN
    INSERT INTO public.user_roles (user_id, role) VALUES (new.id, 'moderator');
  END IF;
  
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = auth, public;

-- Create trigger for new user handling
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- Create helper function for creating test users
CREATE OR REPLACE FUNCTION public.create_user(
    email text
) RETURNS uuid
    SECURITY DEFINER
    SET search_path = auth
AS $$
  DECLARE
  user_id uuid;
BEGIN
  user_id := extensions.uuid_generate_v4();
  
  INSERT INTO auth.users (id, email)
    VALUES (user_id, email)
    RETURNING id INTO user_id;

  RETURN user_id;
END;
$$ LANGUAGE plpgsql; 