-- Create direct_messages table if it doesn't exist
CREATE TABLE IF NOT EXISTS public.direct_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    recipient_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    attachments JSONB,
    inserted_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Add RLS policies if they don't exist
DO $$ 
BEGIN
    -- Enable RLS
    IF NOT EXISTS (
        SELECT 1 FROM pg_tables 
        WHERE schemaname = 'public' 
        AND tablename = 'direct_messages' 
        AND rowsecurity = true
    ) THEN
        ALTER TABLE public.direct_messages ENABLE ROW LEVEL SECURITY;
    END IF;

    -- Add read policy
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE schemaname = 'public' 
        AND tablename = 'direct_messages' 
        AND policyname = 'Users can read their own direct messages'
    ) THEN
        CREATE POLICY "Users can read their own direct messages"
            ON public.direct_messages
            FOR SELECT
            USING (
                auth.uid() = sender_id OR 
                auth.uid() = recipient_id
            );
    END IF;

    -- Add insert policy
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE schemaname = 'public' 
        AND tablename = 'direct_messages' 
        AND policyname = 'Users can insert messages they send'
    ) THEN
        CREATE POLICY "Users can insert messages they send"
            ON public.direct_messages
            FOR INSERT
            WITH CHECK (
                auth.uid() = sender_id
            );
    END IF;

    -- Add delete policy
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE schemaname = 'public' 
        AND tablename = 'direct_messages' 
        AND policyname = 'Users can delete their own sent messages'
    ) THEN
        CREATE POLICY "Users can delete their own sent messages"
            ON public.direct_messages
            FOR DELETE
            USING (
                auth.uid() = sender_id
            );
    END IF;
END $$;

-- Add indexes if they don't exist
CREATE INDEX IF NOT EXISTS direct_messages_sender_id_idx ON public.direct_messages(sender_id);
CREATE INDEX IF NOT EXISTS direct_messages_recipient_id_idx ON public.direct_messages(recipient_id);
CREATE INDEX IF NOT EXISTS direct_messages_inserted_at_idx ON public.direct_messages(inserted_at);

-- Add function to update updated_at timestamp
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Add trigger if it doesn't exist
DO $$ 
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_trigger 
        WHERE tgname = 'handle_direct_messages_updated_at'
    ) THEN
        CREATE TRIGGER handle_direct_messages_updated_at
            BEFORE UPDATE ON public.direct_messages
            FOR EACH ROW
            EXECUTE PROCEDURE public.handle_updated_at();
    END IF;
END $$; 